name: Bi daily Scheduled Script Execution

on:
  schedule:
    - cron: "20 11 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.3.1' 

    - name: Install R packages
      run: | 
             "install.packages(c('tidyverse', 'httr', 'rvest', 'tidyr'))"
      shell: Rscript {0}

    - name: Run bi_daily_grab.R
      run: |
            source("bi_daily_grab.R")
      shell: Rscript {0}
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'SamStruthers'
        git config --global user.email 'sam.struthers2000@gmail.com'
        git add SF_data_archive.csv  # Replace with your actual file name
        git commit -m "Update CSV file after bi daily pull"
        git push
